/** @file Language context providing i18n for Hebrew and Arabic. Exposes t(), language, direction, and toggleLanguage. */

import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_STORAGE_KEY = "biobot-language";
const defaultLanguage = "he";
const supportedLanguages = ["he", "ar"];

const translations = {
  he: {
    shalom: "שלום",
    welcome: "ברוכים הבאים למערכת ביו-בוט",
    homePage: "עמוד הבית",
    searchPage: "חיפוש",
    searchDesc: "חיפוש קורסים",
    bioBotPage: "ביו-בוט",
    bioBotDesc: "מעבר לצ'אט האקדמי החכם",
    formsPage:"נהלים וטפסים",
    formsDesc: "חיפוש טפסים ונהלים אקדמיים",
    logout: "התנתק",
    homePageBtn: "דף הבית",
    profilePage: "פרופיל אישי",
    profileDesc: "צפייה בפרטים האישיים שלך",
    privateDetails: "פרטים אישיים",
    homeButton: "דף הבית",
    stdname: "שם",
    stdEmail: "אימייל",
    stdRole: "תפקיד",
    stdDept: "מחלקה",
    stdYear: "שנה",
    studentFallback: "סטודנט",
    departmentFallback: "הנדסת ביוטכנולוגיה",
    yearFallback: "שנה ב׳",
    loading: "טוען...",
    notFound: "לא נמצא",
    gradeDistribution: "התפלגות ציונים",
    coursesLabel: "קורסים",
    credits: "נק״ז",
    points: "נקודות זכות",
    averageGrade: "ממוצע ציונים",
    courses: "קורסים",
    coursesDone: "קורסים שהושלמו",
    courseName: "שם הקורס",
    courseGrade: "ציון",
    searchCourses: "חיפוש קורסים",
    searchByField: "חפש קורס לפי שדה",
    courseName: "שם הקורס",
    semester: "סמסטר",
    courseCode: "קוד קורס",
    lecturer: "מרצה",
    searchResults: "תוצאות חיפוש קורסים",
    showingCourses: "מוצג {count} קורסים מתוך {total}",
    noResults: "לא נמצאו קורסים התואמים את חיפושך.",
    formsSearchPlaceholder: "חיפוש טופס או נוהל...",
    searchButton: "חיפוש",
    formsLoading: "טוען טפסים...",
    formsLoadError: "שגיאה בטעינת הטפסים. אנא נסה שוב מאוחר יותר.",
    formsEmpty: "לא נמצאו טפסים תואמים.",
    openFile: "פתח קובץ",
    formFileMissing: "קובץ לא נמצא עבור טופס זה",
    bioBotWelcome: "שלום, אני ביו־בוט. איך אוכל לעזור לך בנושא נהלים, טפסים או מידע אקדמי?",
    bioBotTitle: "צ׳אט אקדמי חכם",
    bioBotSubtitle: "שאל שאלות על נהלים, טפסים, בחינות ומצב אקדמי",
    bioBotSuggestedForm: "הטופס המתאים:",
    bioBotOpenSuggestedForm: "פתח קובץ",
    bioBotError: "אירעה שגיאה בקבלת תשובה מהמערכת. נסה שוב.",
    bioBotPlaceholder: "כתוב שאלה לביו-בוט...",
    bioBotThinking: "חושב...",
    bioBotSend: "שליחה",
    newChat: "שיחה חדשה",
    chatHistory: "היסטוריית שיחות",
    noChats: "עדיין אין שיחות.",
    deleteChat: "מחק שיחה",
    notFoundTitle: "העמוד לא נמצא",
    notFoundHeading: "אופס, אין כאן שום דבר",
    notFoundDescription: "הקישור שפתחת לא מוביל לעמוד קיים במערכת ביו-בוט.",
    goToLogin: "לעמוד ההתחברות",
    goToDashboard: "ללוח הניהול",
    goToHome: "לעמוד הבית",
    goBack: "חזרה לעמוד הקודם",
    downloadAcademicPdf: "הורדת PDF למערכת שעות ולקורסים שהושלמו",
    generatingPdf: "מייצר קובץ PDF...",
    pdfGenerationFailed: "יצירת קובץ PDF נכשלה. נסה שוב.",
    currentLanguage: "עברית",
    languageName: "עברית",
    loginTitle: "התחברות",
    loginWelcome: "ברוכים הבאים למערכת ביו־בוט",
    loginEmail: "אימייל",
    loginEmailPlaceholder: "הכנס אימייל",
    loginPassword: "סיסמה",
    loginPasswordPlaceholder: "הכנס סיסמה",
    loginButton: "התחברות",
    loginCreateAccount: "יצירת חשבון חדש",
    loginBrandWelcome: "ברוכים הבאים למערכת ביו־בוט",
    loginBrandSub: "המידע האקדמי שלך, פשוט ונגיש במקום אחד",
    signupTitle: "הרשמה",
    signupWelcome: "צרו חשבון חדש במערכת ביו־בוט",
    signupFirstName: "שם פרטי",
    signupFirstNamePlaceholder: "הכנס שם פרטי",
    signupLastName: "שם משפחה",
    signupLastNamePlaceholder: "הכנס שם משפחה",
    signupEmail: "אימייל",
    signupEmailPlaceholder: "הכנס אימייל",
    signupPassword: "סיסמה",
    signupPasswordPlaceholder: "הכנס סיסמה",
    signupSemester: "סמסטר",
    signupSemesterPlaceholder: "בחר סמסטר (1-8)",
    signupSemesterOption: "סמסטר {n}",
    signupButton: "יצירת חשבון",
    signupHaveAccount: "כבר יש לך חשבון? התחברות",
    signupBrandWelcome: "הצטרפות למערכת ביו־בוט",
    signupBrandSub: "גישה מהירה למידע אקדמי, נהלים וטפסים במקום אחד",
    loginFieldsRequired: "יש להזין אימייל וסיסמה.",
    signupFieldsRequired: "יש למלא את כל השדות.",
    scheduleTitle: "מערכת שעות הרצאות",
    scheduleTimeHeader: "שעה",
    scheduleEmpty: "אין נתוני מערכת שעות זמינים כרגע",
    sortByName: "מיון לפי שם הקורס",
    sortByGrade: "מיון לפי ציון",
    coursesEmpty: "עדיין לא הושלמו קורסים — הציונים יופיעו כאן לאחר תום הסמסטר הראשון.",
    themeLight: "מצב בהיר",
    themeDark: "מצב כהה",
    switchLanguage: "עבור ל{lang}",
    footerCollegeLink: "כניסה למערכות המכללה",
    captchaLabel: "אימות CAPTCHA",
    captchaPlaceholder: "הכנס את התשובה",
    captchaMaxAttempts: "חרגת ממספר הניסיונות המותר. רענן את השאלה ונסה שוב.",
    captchaNotNumber: "יש להזין תשובה מספרית.",
    captchaMaxAttemptsRefresh: "חרגת ממספר הניסיונות המותר. לחץ רענון לקבלת שאלה חדשה.",
    captchaWrongAnswer: "תשובת CAPTCHA שגויה. נשארו {remaining} ניסיונות.",
    adminDashboardTitle: "לוח ניהול",
    adminLogout: "התנתק",
    adminGreeting: "שלום {name} 👋",
    adminWelcome: "ברוכים הבאים ללוח הניהול של מערכת ביו-בוט",
    adminStatStudents: "סטודנטים",
    adminStatForms: "טפסים",
    adminStatQuestions: "שאלות",
    adminStatChats: "שיחות",
    adminNavFormsTitle: "ניהול טפסים",
    adminNavFormsDesc: "הוספה, עריכה ומחיקה של טפסים",
    adminNavUsersTitle: "ניהול משתמשים",
    adminNavUsersDesc: "צפייה במשתמשים והרשאות",
    adminNavStatsTitle: "סטטיסטיקות",
    adminNavStatsDesc: "נתוני שימוש ושאלות נפוצות",
    adminFormsTitle: "ניהול טפסים",
    adminFormsBack: "לוח ניהול",
    adminFormsExisting: "טפסים קיימים",
    adminFormsNone: "אין טפסים במערכת.",
    adminFormsNoCategory: "ללא קטגוריה",
    adminFormsOpen: "פתח",
    adminFormsUpdateBtn: "עדכן",
    adminFormsDeleteBtn: "מחק",
    adminFormsAddTitle: "הוספת טופס חדש",
    adminFormsEditTitle: "עדכון טופס",
    adminFormsSubtitle: "כאן ניתן להעלות קובצי PDF או Word למערכת",
    adminFormsFieldName: "שם הטופס",
    adminFormsFieldNamePlaceholder: "לדוגמה: טופס ערעור",
    adminFormsFieldDesc: "תיאור",
    adminFormsFieldDescPlaceholder: "תיאור קצר של הטופס",
    adminFormsFieldCategory: "קטגוריה",
    adminFormsFieldCategoryPlaceholder: "בחינות / אקדמי / משמעת",
    adminFormsFileLabel: "העלאת קובץ",
    adminFormsFileNote: "אם לא תבחר קובץ חדש, הקובץ הקיים יישאר.",
    adminFormsSaveBtn: "שמור עדכון",
    adminFormsAddBtn: "הוסף טופס",
    adminFormsCancelEdit: "ביטול עריכה",
    adminFormsUpdated: "הטופס עודכן בהצלחה",
    adminFormsAdded: "הטופס נוסף בהצלחה",
    adminFormsDeleted: "הטופס נמחק בהצלחה",
    adminFormsDeleteConfirm: "האם אתה בטוח שברצונך למחוק את הטופס?",
    adminUsersTitle: "ניהול משתמשים",
    adminUsersBack: "לוח ניהול",
    adminUsersLoading: "טוען משתמשים...",
    adminUsersStudentsTitle: "סטודנטים",
    adminUsersStudentsDesc: "חיפוש ומיון משתמשים מסוג סטודנט",
    adminUsersSearchPlaceholder: "חיפוש לפי שם או אימייל...",
    adminUsersSortNewest: "מהחדש לישן",
    adminUsersSortOldest: "מהישן לחדש",
    adminUsersSortName: "מיון אלפביתי",
    adminUsersNoStudents: "לא נמצאו סטודנטים.",
    adminUsersAdminsTitle: "מנהלים",
    adminUsersAdminsDesc: "משתמשים בעלי הרשאות ניהול",
    adminUsersNoAdmins: "אין מנהלים במערכת.",
    adminUsersCreatedAt: "נוצר בתאריך:",
    adminUsersNotAvailable: "לא זמין",
    adminUsersChangeRole: "שינוי הרשאה",
    adminUsersDeleteBtn: "מחק",
    adminUsersCannotDeleteSelf: "לא ניתן למחוק את המשתמש שמחובר כרגע.",
    adminUsersConfirmRole: "האם לשנות את ההרשאה של {name} ל-{role}?",
    adminUsersConfirmDelete: "האם למחוק את המשתמש {name}?",
    adminStatsTitle: "סטטיסטיקות מערכת",
    adminStatsBack: "לוח ניהול",
    adminStatsError: "שגיאה בטעינת הסטטיסטיקות",
    adminStatQuestionsFull: "שאלות בביו־בוט",
    adminStatsTopQuestions: "שאלות נפוצות בביו־בוט",
    adminStatsLoading: "טוען...",
    adminStatsNoQuestions: "עדיין אין שאלות במערכת.",
    adminStatsLiked: "תשובות שאהבו",
    adminStatsDisliked: "תשובות שלא אהבו",
    adminStatsNoLiked: "עדיין אין תשובות שאהבו.",
    adminStatsNoDisliked: "עדיין אין תשובות שלא אהבו.",
    feedbackLike: "תשובה טובה",
    feedbackDislike: "תשובה לא טובה",
    toastChatDeleted: "השיחה נמחקה",
    toastRoleChanged: "התפקיד עודכן בהצלחה",
    toastUserDeleted: "המשתמש נמחק בהצלחה",
    toastFormSaved: "הטופס נשמר בהצלחה",
    toastFormDeleted: "הטופס נמחק",
    emptyCoursesTitle: "אין קורסים עדיין",
    emptyCoursesDesc: "הקורסים שתסיים יופיעו כאן",
    emptyScheduleTitle: "אין מערכת שעות",
    emptyScheduleDesc: "מערכת השעות שלך תופיע כאן",
    emptyFormsTitle: "אין טפסים",
    emptyFormsDesc: "לא נמצאו טפסים במערכת",
    emptyUsersTitle: "אין סטודנטים",
    emptyUsersDesc: "לא נמצאו סטודנטים רשומים",
    emptyQuestionsTitle: "אין שאלות עדיין",
    emptyQuestionsDesc: "שאלות הסטודנטים יופיעו כאן",
    emptyLikedTitle: "אין תשובות שאהבו",
    emptyLikedDesc: "תשובות שסומנו כטובות יופיעו כאן",
    emptyDislikedTitle: "אין תשובות שלא אהבו",
    emptyDislikedDesc: "תשובות שסומנו כלא טובות יופיעו כאן",
  },
  ar: {
    shalom: "مرحبا",
    welcome: "مرحبا بك في بيو-بوت",
    homePage: "الصفحة الرئيسية",
    searchPage: "بحث",
    searchDesc: "البحث عن الكورسات",
    bioBotPage: "بيو-بوت",  
    bioBotDesc: "الانتقال إلى الدردشة الذكية الأكاديمية",
    formsPage: "النماذج والإجراءات",
    formsDesc: "البحث عن النماذج والإجراءات الأكاديمية",
    logout: "الخروج",
    homePageBtn: "الصفحة الرئيسية",
    profilePage: "البروفيل",
    profileDesc: "عرض تفاصيلك الشخصية",
    privateDetails: "تفاصيل شخصية",
    homeButton: "الصفحة الرئيسية",
    stdname: "الاسم",
    stdEmail: "البريد الإلكتروني",
    stdRole: "الدور",
    stdDept: "القسم",
    stdYear: "السنة",
    studentFallback: "סטודנט",
    departmentFallback: "הנדסת ביוטכנולוגיה",
    yearFallback: "שנה ב׳",
    loading: "جارٍ التحميل...",
    notFound: "غير موجود",
    gradeDistribution: "توزيع الدرجات",
    coursesLabel: "الكورسات",
    credits: "النقاط",
    points: "نقاط ",
    averageGrade: "متوسط الدرجات",
    courses: "الكورسات",
    coursesDone: "الكورسات المكتملة",
    courseName: "اسم الكورس",
    courseGrade: "الدرجة",
    searchCourses: "بحث عن الكورسات",
    searchByField: "ابحث عن كورس حسب الحقل",
    courseName: "اسم الكورس",
    semester: "الفصل الدراسي",
    courseCode: "رمز الكورس",
    lecturer: "المحاضر",
    searchResults: "نتائج بحث الكورسات",
    showingCourses: "عرض {count} كورسات من أصل {total}",
    noResults: "لم يتم العثور على كورسات مطابقة.",
    formsSearchPlaceholder: "ابحث عن نموذج أو إجراء...",
    searchButton: "بحث",
    formsLoading: "جارٍ تحميل النماذج...",
    formsLoadError: "حدث خطأ أثناء تحميل النماذج. حاول مرة أخرى لاحقًا.",
    formsEmpty: "لم يتم العثور على نماذج مطابقة.",
    openFile: "افتح الملف",
    formFileMissing: "لا يوجد ملف لهذا النموذج",
    bioBotWelcome: "مرحبا، أنا بيو-بوت. كيف يمكنني مساعدتك بخصوص الإجراءات أو النماذج أو المعلومات الأكاديمية؟",
    bioBotTitle: "دردشة أكاديمية ذكية",
    bioBotSubtitle: "اسأل عن الإجراءات والنماذج والامتحانات ووضعك الأكاديمي",
    bioBotSuggestedForm: "النموذج المناسب:",
    bioBotOpenSuggestedForm: "افتح الملف",
    bioBotError: "حدث خطأ أثناء الحصول على رد من النظام. حاول مرة أخرى.",
    bioBotPlaceholder: "اكتب سؤالك إلى بيو-بوت...",
    bioBotThinking: "يفكر...",
    bioBotSend: "إرسال",
    newChat: "محادثة جديدة",
    chatHistory: "سجل المحادثات",
    noChats: "لا توجد محادثات بعد.",
    deleteChat: "احذف المحادثة",
    notFoundTitle: "الصفحة غير موجودة",
    notFoundHeading: "عذرًا، لا يوجد شيء هنا",
    notFoundDescription: "الرابط الذي فتحته لا يؤدي إلى صفحة موجودة في نظام بيو-بوت.",
    goToLogin: "إلى صفحة تسجيل الدخول",
    goToDashboard: "إلى لوحة الإدارة",
    goToHome: "إلى الصفحة الرئيسية",
    goBack: "العودة إلى الصفحة السابقة",
    downloadAcademicPdf: "تنزيل PDF للجدول والكورسات المكتملة",
    generatingPdf: "جارٍ إنشاء ملف PDF...",
    pdfGenerationFailed: "فشل إنشاء ملف PDF. حاول مرة أخرى.",
    currentLanguage: "العربية",
    languageName: "العربية",
    loginTitle: "تسجيل الدخول",
    loginWelcome: "مرحبا بك في بيو-بوت",
    loginEmail: "البريد الإلكتروني",
    loginEmailPlaceholder: "أدخل البريد الإلكتروني",
    loginPassword: "كلمة المرور",
    loginPasswordPlaceholder: "أدخل كلمة المرور",
    loginButton: "تسجيل الدخول",
    loginCreateAccount: "إنشاء حساب جديد",
    loginBrandWelcome: "مرحبا بك في بيو-بوت",
    loginBrandSub: "معلوماتك الأكاديمية، بسيطة وفي مكان واحد",
    signupTitle: "التسجيل",
    signupWelcome: "أنشئ حسابًا جديدًا في بيو-بوت",
    signupFirstName: "الاسم الأول",
    signupFirstNamePlaceholder: "أدخل الاسم الأول",
    signupLastName: "اسم العائلة",
    signupLastNamePlaceholder: "أدخل اسم العائلة",
    signupEmail: "البريد الإلكتروني",
    signupEmailPlaceholder: "أدخل البريد الإلكتروني",
    signupPassword: "كلمة المرور",
    signupPasswordPlaceholder: "أدخل كلمة المرور",
    signupSemester: "الفصل الدراسي",
    signupSemesterPlaceholder: "اختر الفصل الدراسي (1-8)",
    signupSemesterOption: "الفصل الدراسي {n}",
    signupButton: "إنشاء حساب",
    signupHaveAccount: "هل لديك حساب بالفعل؟ تسجيل الدخول",
    signupBrandWelcome: "انضم إلى بيو-بوت",
    signupBrandSub: "وصول سريع للمعلومات الأكاديمية والنماذج في مكان واحد",
    loginFieldsRequired: "يجب إدخال البريد الإلكتروني وكلمة المرور.",
    signupFieldsRequired: "يجب ملء جميع الحقول.",
    scheduleTitle: "جدول المحاضرات",
    scheduleTimeHeader: "الوقت",
    scheduleEmpty: "لا يوجد جدول متاح",
    sortByName: "ترتيب حسب اسم الكورس",
    sortByGrade: "ترتيب حسب الدرجة",
    coursesEmpty: "لم تُكتمل أي كورسات بعد — ستظهر الدرجات هنا بعد نهاية الفصل الأول.",
    themeLight: "الوضع الفاتح",
    themeDark: "الوضع الداكن",
    switchLanguage: "التبديل إلى {lang}",
    footerCollegeLink: "الدخول إلى أنظمة الكلية",
    captchaLabel: "التحقق من CAPTCHA",
    captchaPlaceholder: "أدخل الإجابة",
    captchaMaxAttempts: "لقد تجاوزت عدد المحاولات المسموح بها. جدد السؤال وحاول مرة أخرى.",
    captchaNotNumber: "يجب إدخال إجابة رقمية.",
    captchaMaxAttemptsRefresh: "لقد تجاوزت عدد المحاولات المسموح بها. اضغط تحديث للحصول على سؤال جديد.",
    captchaWrongAnswer: "إجابة CAPTCHA خاطئة. تبقى {remaining} محاولات.",
    adminDashboardTitle: "لوحة الإدارة",
    adminLogout: "تسجيل الخروج",
    adminGreeting: "مرحبا {name} 👋",
    adminWelcome: "مرحبا بك في لوحة إدارة نظام بيو-بوت",
    adminStatStudents: "الطلاب",
    adminStatForms: "النماذج",
    adminStatQuestions: "الأسئلة",
    adminStatChats: "المحادثات",
    adminNavFormsTitle: "إدارة النماذج",
    adminNavFormsDesc: "إضافة وتعديل وحذف النماذج",
    adminNavUsersTitle: "إدارة المستخدمين",
    adminNavUsersDesc: "عرض المستخدمين والصلاحيات",
    adminNavStatsTitle: "الإحصائيات",
    adminNavStatsDesc: "بيانات الاستخدام والأسئلة الشائعة",
    adminFormsTitle: "إدارة النماذج",
    adminFormsBack: "لوحة الإدارة",
    adminFormsExisting: "النماذج الموجودة",
    adminFormsNone: "لا توجد نماذج في النظام.",
    adminFormsNoCategory: "بدون تصنيف",
    adminFormsOpen: "فتح",
    adminFormsUpdateBtn: "تحديث",
    adminFormsDeleteBtn: "حذف",
    adminFormsAddTitle: "إضافة نموذج جديد",
    adminFormsEditTitle: "تحديث نموذج",
    adminFormsSubtitle: "يمكنك هنا رفع ملفات PDF أو Word إلى النظام",
    adminFormsFieldName: "اسم النموذج",
    adminFormsFieldNamePlaceholder: "مثال: نموذج الاستئناف",
    adminFormsFieldDesc: "الوصف",
    adminFormsFieldDescPlaceholder: "وصف مختصر للنموذج",
    adminFormsFieldCategory: "التصنيف",
    adminFormsFieldCategoryPlaceholder: "امتحانات / أكاديمي / انضباط",
    adminFormsFileLabel: "رفع ملف",
    adminFormsFileNote: "إذا لم تختر ملفًا جديدًا، سيبقى الملف الحالي.",
    adminFormsSaveBtn: "حفظ التحديث",
    adminFormsAddBtn: "إضافة نموذج",
    adminFormsCancelEdit: "إلغاء التعديل",
    adminFormsUpdated: "تم تحديث النموذج بنجاح",
    adminFormsAdded: "تمت إضافة النموذج بنجاح",
    adminFormsDeleted: "تم حذف النموذج بنجاح",
    adminFormsDeleteConfirm: "هل أنت متأكد أنك تريد حذف هذا النموذج؟",
    adminUsersTitle: "إدارة المستخدمين",
    adminUsersBack: "لوحة الإدارة",
    adminUsersLoading: "جاري تحميل المستخدمين...",
    adminUsersStudentsTitle: "الطلاب",
    adminUsersStudentsDesc: "البحث وفرز المستخدمين من نوع طالب",
    adminUsersSearchPlaceholder: "البحث بالاسم أو البريد الإلكتروني...",
    adminUsersSortNewest: "من الأحدث إلى الأقدم",
    adminUsersSortOldest: "من الأقدم إلى الأحدث",
    adminUsersSortName: "ترتيب أبجدي",
    adminUsersNoStudents: "لم يتم العثور على طلاب.",
    adminUsersAdminsTitle: "المديرون",
    adminUsersAdminsDesc: "مستخدمون بصلاحيات إدارية",
    adminUsersNoAdmins: "لا يوجد مديرون في النظام.",
    adminUsersCreatedAt: "تاريخ الإنشاء:",
    adminUsersNotAvailable: "غير متاح",
    adminUsersChangeRole: "تغيير الصلاحية",
    adminUsersDeleteBtn: "حذف",
    adminUsersCannotDeleteSelf: "لا يمكن حذف المستخدم المسجل حاليًا.",
    adminUsersConfirmRole: "هل تريد تغيير صلاحية {name} إلى {role}؟",
    adminUsersConfirmDelete: "هل تريد حذف المستخدم {name}؟",
    adminStatsTitle: "إحصائيات النظام",
    adminStatsBack: "لوحة الإدارة",
    adminStatsError: "خطأ في تحميل الإحصائيات",
    adminStatQuestionsFull: "أسئلة بيو-بوت",
    adminStatsTopQuestions: "الأسئلة الشائعة في بيو-بوت",
    adminStatsLoading: "جاري التحميل...",
    adminStatsNoQuestions: "لا توجد أسئلة في النظام بعد.",
    adminStatsLiked: "الإجابات التي أُعجب بها",
    adminStatsDisliked: "الإجابات التي لم تُعجب",
    adminStatsNoLiked: "لا توجد إجابات معجب بها بعد.",
    adminStatsNoDisliked: "لا توجد إجابات غير معجب بها بعد.",
    feedbackLike: "إجابة جيدة",
    feedbackDislike: "إجابة غير جيدة",
    toastChatDeleted: "تم حذف المحادثة",
    toastRoleChanged: "تم تحديث الدور بنجاح",
    toastUserDeleted: "تم حذف المستخدم بنجاح",
    toastFormSaved: "تم حفظ النموذج بنجاح",
    toastFormDeleted: "تم حذف النموذج",
    emptyCoursesTitle: "لا توجد مقررات بعد",
    emptyCoursesDesc: "ستظهر المقررات التي أتممتها هنا",
    emptyScheduleTitle: "لا يوجد جدول دراسي",
    emptyScheduleDesc: "سيظهر جدولك الدراسي هنا",
    emptyFormsTitle: "لا توجد نماذج",
    emptyFormsDesc: "لم يتم العثور على نماذج في النظام",
    emptyUsersTitle: "لا يوجد طلاب",
    emptyUsersDesc: "لم يتم العثور على طلاب مسجلين",
    emptyQuestionsTitle: "لا توجد أسئلة بعد",
    emptyQuestionsDesc: "ستظهر أسئلة الطلاب هنا",
    emptyLikedTitle: "لا توجد إجابات معجب بها",
    emptyLikedDesc: "ستظهر الإجابات المُقيَّمة بشكل إيجابي هنا",
    emptyDislikedTitle: "لا توجد إجابات غير معجب بها",
    emptyDislikedDesc: "ستظهر الإجابات المُقيَّمة بشكل سلبي هنا",
  },
};

const LanguageContext = createContext({
  language: defaultLanguage,
  direction: "rtl",
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key, params) => key,
  currentLanguageLabel: translations[defaultLanguage].currentLanguage,
  nextLanguageLabel: translations["ar"].languageName,
});

/** Wraps the app and provides language state. Persists the selected language to localStorage. */
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      const saved = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
      return supportedLanguages.includes(saved) ? saved : defaultLanguage;
    } catch (error) {
      return defaultLanguage;
    }
  });

  useEffect(() => {
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    } catch (error) {
      console.warn("Unable to persist language selection.", error);
    }
  }, [language]);

  const value = useMemo(() => {
    const toggleLanguage = () => {
      setLanguage((prevLanguage) =>
        prevLanguage === "he" ? "ar" : "he"
      );
    };

    const currentTranslation = translations[language] || translations[defaultLanguage];
    const nextLanguage = language === "he" ? "ar" : "he";

    return {
      language,
      direction: language === "ar" || language === "he" ? "rtl" : "ltr",
      setLanguage,
      toggleLanguage,
      t: (key, params = {}) => {
        const template = currentTranslation[key] || translations[defaultLanguage][key] || key;
        return Object.entries(params).reduce(
          (text, [paramKey, paramValue]) =>
            text.replace(`{${paramKey}}`, paramValue),
          template
        );
      },
      currentLanguageLabel: currentTranslation.currentLanguage,
      nextLanguageLabel: translations[nextLanguage]?.languageName || nextLanguage,
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

/** Returns { language, direction, t, toggleLanguage, currentLanguageLabel, nextLanguageLabel }. */
export function useLanguage() {
  return useContext(LanguageContext);
}